// AUTOGENERATED, DO NOT CHANGE MANUALLY

import authRu from './ru/auth.json';
import bannedRu from './ru/banned.json';
import calcRu from './ru/calc.json';
import huntRu from './ru/hunt.json';
import infoRu from './ru/info.json';
import mainRu from './ru/main.json';
import validationRu from './ru/validation.json';
import authEn from './en/auth.json';
import bannedEn from './en/banned.json';
import calcEn from './en/calc.json';
import huntEn from './en/hunt.json';
import infoEn from './en/info.json';
import mainEn from './en/main.json';
import validationEn from './en/validation.json';

export {
	authRu,
	bannedRu,
	calcRu,
	huntRu,
	infoRu,
	mainRu,
	validationRu,
	authEn,
	bannedEn,
	calcEn,
	huntEn,
	infoEn,
	mainEn,
	validationEn
};
